name: CI

on: [push]

jobs:
  docker_image_scout:
    name: Build and Scan a Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #We can first see if there is already
      #a pre-installed Docker version
      - name: Check Docker Version
        id: check_docker
        continue-on-error: true
        run: docker version

      #only if the previous step fails this one will be taken into action
      - name: Set up Docker (if missing)
        if: steps.check_docker.outcome == 'failure'
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker_version: '28.0.1'

      #- name: Build Docker Image
      #  run: docker build -f Dockerfile -t whale . 
        
      #then login to docker, to siccessfully runt he docker scout
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Docker Image
        run: docker build -f Dockerfile -t ${{ secrets.USERNAME }}/whale:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.username }}/whale
          
      # Scan with Docker Scout
      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare,sbom
          image: ${{ secrets.username }}/whale  # ✅ Now scanning a public image
          #image: whale  # ✅ Scan the built image
          exit-code: false  # Don't fail the workflow if CVEs are found
          sarif-file: sca_scout.sarif
          output: sbom_scout.spdx.json
          format: spdx

      # Upload SBOM (Software Bill of Materials) as an artifact
      - name: Upload SBOM file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom_scout.spdx.json
          path: sbom_scout.spdx.json

      # Upload SARIF file (Security Analysis Report)
      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sca_scout.sarif
          path: sca_scout.sarif

      # Upload SARIF report to GitHub Security tab (for public repos or GitHub Enterprise)
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sca_scout.sarif
          category: Security/SCA

      # Submit SBOM data to GitHub's dependency graph
      - name: SBOM upload
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1
