name: CI

on: [push]

jobs:
  docker_image_scout:
    name: Build and Scan a Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #We can first see if there is already
      #a pre-installed Docker version
      - name: Check Docker Version
        id: check_docker
        continue-on-error: true
        run: docker version

      #only if the previous step fails this one will be taken into action
      - name: Set up Docker (if missing)
        if: steps.check_docker.outcome == 'failure'
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker_version: '28.0.1'

      - name: Build Docker Image
        run: docker build -f Dockerfile -t whale:latest . 

      - name: Docker Scout
        uses: docker/scout-action@v1

      - name: Docker Scout scan
        run: |
          
